### ISSUE TITLE
The flag icon in readme

### ISSUE THREAD

**Issue by FarooqAR** [urduhack/urduhack#20]
As much as we love Pakistan and would want its flag everywhere, the Urdu language is not exclusive to Pakistan and is spoken, read and written in other parts of the world, particularly India as well. It'd be really nice if it is omitted from the title and anywhere else.

Regards,
A Pakistani

**Comment by rayyan17** [comment]
I would like to clarify your concern about this:
- Even though Urdu is spoken in other countries, it is the official language of Pakistan
- Data collected and trained for this problem was explicitly from the style and semantics of Urdu being used in Pak
- Urdu is a mixture of different language, so its style varies in different regions
- The purpose to represent Pakistan was not just about using country name everywhere but to make them aware of the context of data
- The understanding and knowing the background of data is very important before randomly using it.

**Comment by akkefa** [comment]
@FarooqAR I hope you understand the point.

**Comment by FarooqAR** [comment]
Yes, that clarifies my concern. Thank You. The project already encouraged me to contribute to it  :+1:
